linters:
  enable:
    - gosec
    - misspell
    - sqlclosecheck
    - errorlint
    - exhaustive
    - gocritic

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gosec:
    excludes:
      - G101 # Potential hardcoded credentials (false positives)
      - G402 # TLS MinVersion too low
      #- G115 # integer overflow conversion (TODO: verify these)
      - G204 # iSubprocess launched with a potential tainted input or cmd arguments
