receivers:
  otlp:
    protocols:
      http:
        endpoint: :4318
      grpc:
        endpoint: :4317

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
